import { useEffect,useRef,useState } from 'react';
import type { FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { siteContent as s,treatments } from '../data/siteContent';
import { Button,Container,SectionHeader } from './Primitives';
type Field = keyof typeof s.form.errors;
export function ContactForm(){const [params]=useSearchParams();const [errors,setErrors]=useState<Partial<Record<Field,string>>>({});const [success,setSuccess]=useState(false);const successRef=useRef<HTMLParagraphElement>(null);useEffect(()=>{if(success)successRef.current?.focus();},[success]);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const value=(key:string)=>String(data.get(key)??'').trim();const next:Partial<Record<Field,string>>={};if(value('name').length<2)next.name=s.form.errors.name;if(!/^\d{10,11}$/.test(value('whatsapp').replace(/\D/g,'')))next.whatsapp=s.form.errors.whatsapp;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value('email')))next.email=s.form.errors.email;if(!value('treatment'))next.treatment=s.form.errors.treatment;if(!value('period'))next.period=s.form.errors.period;if(!data.get('consent'))next.consent=s.form.errors.consent;setErrors(next);if(Object.keys(next).length){setSuccess(false);const first=Object.keys(next)[0];(form.elements.namedItem(first) as HTMLElement|null)?.focus();return;}form.reset();setSuccess(true);}
const fieldProps=(key:Field)=>({id:`contact-${key}`,name:key,'aria-invalid':Boolean(errors[key]),'aria-describedby':errors[key]?`error-${key}`:undefined});const error=(key:Field)=>errors[key]&&<span className="field-error" id={`error-${key}`}>{errors[key]}</span>;
return <section className="section form-section" id="avaliacao"><Container><div className="form-layout"><SectionHeader title={s.form.title} description={s.form.description}/><form noValidate onSubmit={submit}><div className="form-grid"><label htmlFor="contact-name">{s.form.name}<input {...fieldProps('name')} autoComplete="name" required maxLength={120}/>{error('name')}</label><label htmlFor="contact-whatsapp">{s.form.whatsapp}<input {...fieldProps('whatsapp')} type="tel" autoComplete="tel-national" inputMode="tel" required maxLength={20}/>{error('whatsapp')}</label><label htmlFor="contact-email">{s.form.email}<input {...fieldProps('email')} type="email" autoComplete="email" required maxLength={160}/>{error('email')}</label><label htmlFor="contact-treatment">{s.form.treatment}<select {...fieldProps('treatment')} defaultValue={treatments.some(t=>t.slug===params.get('tratamento'))?params.get('tratamento')! : ''} required><option value="" disabled>{s.form.choose}</option>{treatments.map(t=><option key={t.slug} value={t.slug}>{t.name}</option>)}<option value="orientation">{s.form.undecided}</option></select>{error('treatment')}</label><label className="full" htmlFor="contact-message">{s.form.message}<textarea id="contact-message" name="message" rows={4} maxLength={2000}/></label><label className="full" htmlFor="contact-period">{s.form.period}<select {...fieldProps('period')} defaultValue="" required><option value="" disabled>{s.form.choose}</option>{s.form.periods.map(x=><option key={x}>{x}</option>)}</select>{error('period')}</label></div><label className="consent" htmlFor="contact-consent"><input {...fieldProps('consent')} type="checkbox" required/>{s.form.consent}</label>{error('consent')}<Button type="submit">{s.form.submit}</Button><p className="small">{s.form.mock}</p>{success&&<p className="success" role="status" tabIndex={-1} ref={successRef}>{s.form.success}</p>}</form></div></Container></section>;}
